TRS_Web/TRS_Web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('Tourism.urls','customer'), namespace = 'customer')),
    path('Tour-Master/',include(('administrator.urls', 'tour-master'), namespace = 'tour-master')),
]

TRS_Web/Tourism/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home_page'),
    path('log-out',views.logOut,name='log-out'),
    path('register_page', views.register, name='register_page'),
    path('login_page', views.login, name='login_page'),
    path('home', views.login_check, name='home'),
    path('registered', views.registered_check, name='registered'),
    path('tour_page', views.tour_page, name='tour_page'),
    path('tour_registration', views.tour_register, name="tour_registration"),
    path('vehicle_page', views.vehicle_page,name='vehicle_page'),
    path('vehicle_register', views.vehicle_registration, name='vehicle_register'),
    path('customer_contact', views.customer_contact, name='customer_contact'),
    path('hotel_book',views.hotel_booked,name='hotel_book'),
    path('hotel',views.hotel_book,name='hotel'),
    path('recommend',views.recommed,name="recommend"),
    path('orders',views.customer_orders,name='orders'),
    path('update-tour/(<int:plan_id>)',views.updateTour,name='update-tour'),
    path('delete-tour/(<int:tour_id>)',views.delete_tour,name='delete-tour'),
]

TRS_Web/Tourism/models.py
from django.db import models


class CustomerDetails(models.Model):
    customer_id = models.AutoField(primary_key=True)
    customer_username = models.CharField(max_length=100, blank=True, null=True)
    customer_name = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)
    mobileno = models.BigIntegerField(blank=True, null=True)
    customer_password = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'customer_details'


class CustomerQuery(models.Model):
    customer = models.ForeignKey(CustomerDetails, models.DO_NOTHING)
    customer_name = models.CharField(max_length=20)
    customer_email = models.CharField(max_length=60)
    customer_number = models.CharField(max_length=11)
    customer_message = models.CharField(max_length=100)
    employee_reply = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'customer_query'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class HotelBooking(models.Model):
    customer = models.ForeignKey(CustomerDetails, models.DO_NOTHING)
    customer_name = models.CharField(max_length=40)
    customer_email = models.CharField(max_length=40)
    customer_number = models.CharField(max_length=11)
    room_booked = models.CharField(max_length=3)
    no_of_people = models.CharField(max_length=3)
    hotel_checkin = models.DateField()
    hotel_checkout = models.DateField()
    date_booked = models.DateField()
    hotel_status = models.IntegerField(db_comment='0 = Approve\r\n1 = Initialise\r\n2 = Denied')

    class Meta:
        managed = False
        db_table = 'hotel_booking'


class Payment(models.Model):
    paid_date = models.DateField(blank=True, null=True)
    paid_amount = models.FloatField(blank=True, null=True)
    paid_status = models.IntegerField()
    paid_by = models.IntegerField(blank=True, null=True)
    tour_id = models.IntegerField()


    class Meta:
        managed = False
        db_table = 'payment'


class TourRegistration(models.Model):
    customer = models.ForeignKey(CustomerDetails, models.DO_NOTHING)
    customer_name = models.CharField(max_length=30)
    customer_email = models.CharField(max_length=60)
    customer_phone = models.CharField(max_length=12)
    customer_address = models.CharField(max_length=100)
    customer_gender = models.CharField(max_length=8)
    customer_country = models.CharField(max_length=20)
    customer_state = models.CharField(max_length=20)
    customer_passport = models.CharField(unique=True, max_length=10)
    customer_selected_package = models.IntegerField()
    trip_startdate = models.DateField()
    trip_enddate = models.DateField()
    trip_amt = models.FloatField()
    customer_payment = models.FloatField()
    trip_status = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'tour_registration'


class TourismPlan(models.Model):
    plan_id = models.AutoField(primary_key=True)
    plan_name = models.CharField(max_length=40, blank=True, null=True)
    plan_details = models.CharField(max_length=200, blank=True, null=True)
    plan_duration = models.CharField(max_length=100, blank=True, null=True)
    plan_amount = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tourism_plan'


class TrsEmployee(models.Model):
    emp_id = models.AutoField(primary_key=True)
    emp_name = models.CharField(max_length=50)
    emp_address = models.CharField(max_length=100)
    emp_dob = models.DateField()
    emp_email = models.CharField(max_length=200)
    emp_mobno = models.BigIntegerField()
    emp_sal = models.FloatField()
    emp_type = models.IntegerField()
    emp_username = models.CharField(max_length=100)
    emp_password = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'trs_employee'


class VehicleRegistration(models.Model):
    customer = models.ForeignKey(CustomerDetails, models.DO_NOTHING)
    customer_name = models.CharField(max_length=50)
    customer_license = models.CharField(unique=True, max_length=16)
    customer_email = models.CharField(max_length=60)
    customer_phone = models.CharField(max_length=11)
    customer_pickup = models.DateField()
    customer_drop = models.DateField()
    vehicle_type = models.CharField(max_length=20)
    city = models.CharField(max_length=15)
    amount = models.FloatField()
    vehicle_status = models.IntegerField(db_comment='0 = Approve\r\n1 = Initialise\r\n2 = Denied')

    class Meta:
        managed = False
        db_table = 'vehicle_registration'

TRS_Web/Tourism/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.db import connection
from django.contrib import messages
import js2py, datetime
from django.utils.datastructures import MultiValueDictKeyError
from django.core.mail import send_mail
from .models import *
import time

# Create your views here.

def home(request):
    return render(request, 'Tourism/index.html')

def login(request):
    return render(request, 'Tourism/login.html')

def register(request):
    return render(request, 'Tourism/login.html')

def customer_orders(request):
    try:
        username = request.session['username']
        customer = CustomerDetails.objects.get(customer_username = username)
        query = "select * from tourism_plan,tour_registration where tour_registration.customer_selected_package = tourism_plan.plan_id AND tour_registration.customer_id = %s" % customer.customer_id
        tour_register = TourRegistration.objects.raw(query)
        hotel_booked = HotelBooking.objects.filter(customer_id=customer.customer_id,).all()
        vehicle_booked = VehicleRegistration.objects.filter(customer_id=customer.customer_id)
        profile = CustomerDetails.objects.get(customer_id=customer.customer_id)
        plans = TourismPlan.objects.all()

        context = {
            'tour_booked' : tour_register,
            'hotel_booked' : hotel_booked ,
            'vehicle_booked' : vehicle_booked , 
            'profile' : profile,
            'plans' : plans,
        }
        return render(request,"Tourism/customer_orders.html",context)
    except KeyError:
        return HttpResponse("<h1>Please Log in </h1><a href='/'>Click Here to Log in</a> ")

def updateTour(request,plan_id):
    startDate =  request.POST['startdate']
    endDate =  request.POST['enddate']
    planed_id = request.POST['plan_id']
    tour = TourRegistration.objects.get(id=plan_id)
    tour.trip_startdate = startDate
    tour.trip_enddate = endDate
    tour.save()
    messages.add_message(request,messages.SUCCESS,"Tour Package Updated")
    return HttpResponseRedirect("/orders")


def registered_check(request):
    custName = request.POST['custname']
    username = request.POST['username']
    email = request.POST['email']
    mobileno = request.POST['mobileno']
    pw = request.POST['pw']
    pw1 = request.POST['pw1']

    if pw != pw1:
        messages.add_message(request,messages.ERROR,"Password Does not Match")
    else:
        csave = CustomerDetails(
            customer_username=username,
            customer_name=custName,
            email = email,
            mobileno=mobileno,
            customer_password=pw
        )
        csave.save()
        msg=custName+", \nThank You For Registering with Us !!\nRegard,\nTRS Team"
        send_mail("Welcome to Tourism Booking",msg,'sachinkalloli932@gmail.com',[email])
        messages.add_message(request,messages.SUCCESS,"Registered Sucessfully !!")
        return HttpResponseRedirect("/")

def delete_tour(request,tour_id):
    tour = TourRegistration.objects.get(id = tour_id)
    tour.delete()
    messages.add_message(request,messages.SUCCESS,"Tour Deleted Successfully")
    return HttpResponseRedirect('/orders')




def login_check(request):
    try:
        customer_id = request.POST.get('useremail')
        customer_pw = request.POST.get('userpw')
        if customer_id == '' and customer_pw == '':
            messages.warning(request, 'Fields Are Empty !!')
            return render(request, 'Tourism/index.html')
        else:
            login  = CustomerDetails.objects.get(customer_username=customer_id,customer_password=customer_pw)
            con = connection.cursor()
            messages.add_message(request,messages.SUCCESS, 'Login Successfully!!')
            request.session['username'] = customer_id   
            return render(request, 'Tourism/index.html')
    except CustomerDetails.DoesNotExist:
        messages.add_message(request,messages.ERROR,"Login Failed !!")
        return HttpResponseRedirect("/")

def tour_page(request):
    plans = TourismPlan.objects.all()
    return render(request, 'Tourism/Tour_Register_new.html',{'plan':plans})


def tour_register(request):
    cfname = request.POST.get('data_3', False)
    clname = request.POST.get('data_4', False)
    cname = str(cfname) + ' ' + str(clname)
    cemail = request.POST.get('data_5', False)
    cphone = request.POST.get('data_6', False)
    caddress = request.POST.get('data_18', False)
    cgender = request.POST.get('data_20', False)
    ccountry = request.POST.get('data_15', False)
    cstate = request.POST.get('data_16', False)
    cpassport = request.POST.get('data_19', False)
    cpackage = request.POST.get('data_21', False)
    cSelectdate = request.POST.get('data_22', False)
    print(cname, cemail, cphone, caddress, cgender, ccountry, cstate, cpassport, cpackage, cSelectdate)
    con = CustomerDetails.objects.get(customer_username=request.session['username'])
    trip_amt = TourismPlan.objects.get(plan_id = cpackage)
    print(trip_amt.plan_amount)
    tour = TourRegistration(
        customer_id = con.customer_id,
        customer_name = cname,
        customer_email = cemail,
        customer_phone = cphone,
        customer_address = caddress,
        customer_gender = cgender,
        customer_country = ccountry,
        customer_state = cstate,
        customer_passport = cpassport,
        customer_selected_package = cpackage,
        trip_startdate = cSelectdate,
        trip_enddate = '2000-10-01',
        trip_amt = trip_amt.plan_amount,
        customer_payment = 0,
        trip_status = 1
    )
    tour.save()
    messages.add_message(request, messages.SUCCESS,'Successfully Registered')
    return render(request, 'Tourism/thanks.html')


def vehicle_page(request):
    return render(request, 'Tourism/vehicle_booking.html')


def vehicle_registration(request):
    try:
        username = request.POST['rental_user_name']
        userdl = request.POST['rental_user_dl']
        vtype = request.POST['vehicle_type']
        useremail = request.POST['rental_user_email']
        userphone = request.POST['rental_user_phone']
        pickup = request.POST['rental_user_pickD']
        drop = request.POST['rental_user_dropD']
        city = request.POST['city']
        amt = request.POST['vamt']
        print(username, userdl, useremail, userphone, vtype, pickup, drop, city, amt)
        q = 'INSERT INTO `vehicle_registration`(`id`, `customer_id`,`customer_name`, `customer_license`, `customer_email`, ' \
            '`customer_phone`, `customer_pickup`, `customer_drop`, `vehicle_type`, `city`, `amount`,`vehicle_status`) VALUES (%s,%s,%s,%s,' \
            '%s,%s,%s,%s,%s,%s,%s,%s) '
        con = CustomerDetails.objects.get(customer_username=request.session['username'])
        v = (0,con.customer_id,username, userdl, useremail, userphone, pickup, drop, vtype, city, amt,1)
        cursor = connection.cursor()
        cursor.execute(q, v)
        messages.success(request, 'Confirmation Will be sent Soon')
        send_mail('Thank You for Contacting Us !', 'We Will Reach out to you Soon!!', 'pavanshinde678@gmail.com', (cemail,), fail_silently=False) 
        return render(request, 'Tourism/thanks.html')

    except:
        messages.success(request, 'Something Went Wrong')
        return render(request, 'Tourism/vehicle_booking.html')


def customer_contact(request):
    name = request.POST['name']
    cemail = request.POST['cemail']
    cnumber = request.POST['cnumber']
    cmsg = request.POST['cmsg']
    print(name, cemail, cnumber, cmsg)
    q = "INSERT INTO `customer_query`(`customer_name`, `customer_email`, `customer_number`, `customer_message`, " \
        "`employee_reply`) VALUES (%s,%s,%s,%s,%s) "
    v = (name, cemail, cnumber, cmsg, '')
    cursor = connection.cursor()
    cursor.execute(q, v)
    messages.success(request, 'Thank You For Enquiry!!') 
    send_mail('Thank You for Contacting Us !', 'We Will Reach out to you Soon!!', 'pavanshinde678@gmail.com', (cemail,), fail_silently=False)   
    return render(request, 'Tourism/thanks.html')

def logOut(request):
    request.session.flush()
    return HttpResponseRedirect("/")

def recommed(request):
    return render(request, 'Tourism/recommed.html')


def hotel_book(request):
    return render(request, 'Tourism/hotel_booking.html')
    
def hotel_booked(request):
    from datetime import date
    d=date.today()
    name = request.POST.get('custname')
    cemail = request.POST.get('cemail')
    cnumber = request.POST.get('cnumber')
    roombkd= request.POST.get('roombkd')
    people=request.POST.get('people')
    checkin=request.POST.get('checkindt')
    checkout=request.POST.get('checkoutdt')
    print(name,cemail,cnumber,roombkd,people,checkin,checkout)
    con = CustomerDetails.objects.get(customer_username=request.session['username'])
    hotel = HotelBooking(
        customer_id = con.customer_id,
        customer_name = name,
        customer_email = cemail,
        customer_number = cnumber,
        room_booked = roombkd,
        no_of_people = people,
        hotel_checkin = checkin,
        hotel_checkout = checkout,
        date_booked = d ,
        hotel_status = 1,
    )
    hotel.save()
    messages.success(request, 'Thank You For Hotel Booking We Will Reach Out to You Soon!!')
    send_mail('Thank You for Contacting Us !', 'We Will Reach out to you Soon!!', 'pavanshinde678@gmail.com', (cemail,), fail_silently=False) 
    time.sleep(3)
    return render(request,"Tourism/thanks.html")

TRS_Web/Tourism/templates/Tourism/Hi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
<h1>Hello My First Web Page in Django</h1>
</body>
</html>

TRS_Web/Tourism/templates/Tourism/Tour_Register_new.html
<!DOCTYPE HTML>
<html>
<head><title>Tour Registration</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>

#fom
{
  border:0 solid black;
  padding:10px;
  width:70%;
  margin-left:15%;
  border-radius:20px;
}

#submit
{
  padding:7px;
  width:120px;
  border-radius:20px;
  border-width:1px;
}

#submit:hover
{
  padding:10px;
  font-weight:bolder;
  
}
tr,td{
	padding: 10px;
 }

 select
 {
  font-weight:bold;
  font-size:14px;
  border-radius:20px;
 }
 #data_23
 {
   font-size:14px;
   font-weight:bold;
 }
body
{
	background: #eee;
}
</style>
</head>
<body>
	{% if 'username' in request.session %}
<div id="fom">
<form method="post" action="{% url 'customer:tour_registration' %}" onSubmit="return validateForm();">
	{% csrf_token %}
	<table>
		<tr>
			<th colspan="4">
					<h2 style="margin-left: 62%;margin-top:2%;font-weight: 500;">Tour Registration</h2>
					<div style="text-align:left; padding-bottom: 15px;font-size : 18px;">&nbsp;
						{% include 'Tourism/messages_block.html' %}</div>
			</th>
		</tr>
		<tr>
			
			<td><b>First name :<span style="color: red;"> *</span></td>
			<td><input type="text" id="data_3" name="data_3" style="max-width: 100%;" class="form-control" required/></td>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td><b>Last name :<span style="color: red;"> *</span></td></b>
			<td> <input type="text" id="data_4" name="data_4" style="max-width: 100%;" class="form-control" required/></td>
		</tr>
		<tr>
			<td><b>Email :<span style="color: red;"> *</span></td></b>
			<td> <input type="email" id="data_5" name="data_5" style="max-width : 450px;" class="form-control" required></td>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td><b>Phone :<span style="color: red;"> *</span></td></b>
			<td> <input type="text" pattern="[789]/d{9}" id="data_6" name="data_6" maxlength="10" style="max-width : 450px;" class="form-control" required></td>
		</tr>
		<tr>
			<td><b>Gender :<span style="color: red;"> *</span></td></b>
			<td><select id="data_20" name="data_20" style="max-width : 450px;" class="form-control" required>
				<option value="">Select Gender</option>
				<option value="Male">Male</option>
				<option value="Female">Female</option>
				</select>
			</td>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td><b>Country :<span style="color: red;"> *</span></td></b>
			<td><select id="data_15" name="data_15" style="max-width : 450px;" class="form-control" required>
					<option value="">Select Country</option>
					<option>India</option>
			</td>
		</tr>
		<tr>
			<td><b>State :</td></b>
			<td> <select id="data_16" name="data_16" style="max-width : 450px;" class="form-control" required>
				<option value="">Select State</option>
				<option value="Andhra Pradesh">Andhra Pradesh</option>
				<option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
				<option value="Arunachal Pradesh">Arunachal Pradesh</option>
				<option value="Assam">Assam</option>
				<option value="Bihar">Bihar</option>
				<option value="Chandigarh">Chandigarh</option>
				<option value="Chhattisgarh">Chhattisgarh</option>
				<option value="Dadar and Nagar Haveli">Dadar and Nagar Haveli</option>
				<option value="Daman and Diu">Daman and Diu</option>
				<option value="Delhi">Delhi</option>
				<option value="Lakshadweep">Lakshadweep</option>
				<option value="Puducherry">Puducherry</option>
				<option value="Goa">Goa</option>
				<option value="Gujarat">Gujarat</option>
				<option value="Haryana">Haryana</option>
				<option value="Himachal Pradesh">Himachal Pradesh</option>
				<option value="Jammu and Kashmir">Jammu and Kashmir</option>
				<option value="Jharkhand">Jharkhand</option>
				<option value="Karnataka">Karnataka</option>
				<option value="Kerala">Kerala</option>
				<option value="Madhya Pradesh">Madhya Pradesh</option>
				<option value="Maharashtra">Maharashtra</option>
				<option value="Manipur">Manipur</option>
				<option value="Meghalaya">Meghalaya</option>
				<option value="Mizoram">Mizoram</option>
				<option value="Nagaland">Nagaland</option>
				<option value="Odisha">Odisha</option>
				<option value="Punjab">Punjab</option>
				<option value="Rajasthan">Rajasthan</option>
				<option value="Sikkim">Sikkim</option>
				<option value="Tamil Nadu">Tamil Nadu</option>
				<option value="Telangana">Telangana</option>
				<option value="Tripura">Tripura</option>
				<option value="Uttar Pradesh">Uttar Pradesh</option>
				<option value="Uttarakhand">Uttarakhand</option>
				<option value="West Bengal">West Bengal</option>
				</select>
			</td>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td><b>Address :<span style="color: red;"> *</span></td></b>
			<td><textarea id="data_18" false name="data_18" style="max-width : 450px;" rows="4" cols="30" class="form-control" required></textarea>
			</td>
		</tr>
		<tr>
			<script>
				function check(){
					var id = document.getElementById("data_21").value;
					
					document.getElementById("data_23").value = id;
				}
			</script>
			<td ><b>Select Tour Package :<span style="color: red;"> *</span></td></b>
			<td><select id="data_21" name="data_21" style="max-width : 450px;" onchange="check();" onclick="check();" class="form-control" required>
				<option value="">Tour Plan with Trip Cost</option>
				{% for i in plan %}
				<option value="{{ i.plan_id }}">{{ i.plan_name }} - {{ i.plan_details }} {{ i.plan_amount}}</option>
				{% endfor %}
		
				</select>
				
			<td>
				<td><b>Select Date :<span style="color: red;"> *</span></td></b></td></b>
				<td> <input type="date" id="data_22"  name="data_22" value="2022-07-20" style="max-width : 450px;width:60%;font-weight:bold;"  class="form-control" required>
				</td>
				
			</td>
			
		</tr>
		<tr>
			<td><b>Passport Number :<span style="color: red;"> *</span></td></b>
			<td> <input type="text" pattern="[A-Z]{1}[0-9]{7}" id="data_19" name="data_19" style="max-width : 450px;" class="form-control" required/>
			</td>
			
		</tr>
		<tr>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td colspan="5"><div style="margin-left:30%;">
					<input name="skip_Submit" class="btn btn-success" id="submit" value="Submit" type="submit" />&nbsp;
					<input name="skip_Submit" class="btn btn-primary" id="submit" value="Reset" type="reset"/>
				</div>
			</td>
		</tr>
	</table>
</form>
</p>
<script type="text/javascript">


function packages()
{
  if(document.getElementById('data_21').value==='Tour Package 1')
  {
  	var a="";
    document.getElementById('data_23').value="Package 1";
  }
  else if(document.getElementById('data_21').value==='Tour Package 2')
  {
    document.getElementById('data_23').value="Package 2";
  }
  else if(document.getElementById('data_21').value==='Tour Package 3')
  {
    document.getElementById('data_23').value="Package 3";
  }
  else
  {
    document.getElementById('data_23').value="Select Package";
  }
}
function validateForm() {


if (isEmpty(document.getElementById('data_3').value.trim())) {
alert('First name is required!');
return false;
}
if (isEmpty(document.getElementById('data_4').value.trim())) {
alert('Last name is required!');
return false;
}
if (isEmpty(document.getElementById('data_5').value.trim())) {
alert('Email is required!');
return false;
}
if (!validateEmail(document.getElementById('data_5').value.trim())) {
alert('Email must be a valid email address!');
return false;
}
if (isEmpty(document.getElementById('data_6').value.trim())) {
alert('Phone is required!');
return false;
}
if (isEmpty(document.getElementById('data_18').value.trim())) {
alert('Address is required!');
return false;
}
if (isEmpty(document.getElementById('data19').value.trim())) {
alert('Passport Number is required!');
return false;
}
if (isEmpty(document.getElementById('data_25').value.trim())) {
alert('Terms and Conditions is required!');
return false;
}
return true;
}
function isEmpty(str) { return (str.length === 0 || !str.trim()); }
function validateEmail(email) {
var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,15}(?:\.[a-z]{2})?)$/i;
return isEmpty(email) || re.test(email);

}
</script>
{%  else %}
<h1>Please Login to Book</h1>
<script>
        window.setTimeout(window.location.href = "/",1000);
</script>
{% endif %}
</body>
</html>

TRS_Web/Tourism/templates/Tourism/message_show.html
	 {% if messages %}
              {%  for message in messages %}
              <ul style="color:black;font-size:12px;margin-left:0%; width:40%;font-weight:bolder;"><li><div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert" style="margin-left:0%;">
                 {{ message }}
              </div></li></ul>
              {% endfor %}
			{% endif %}

TRS_Web/Tourism/templates/Tourism/messages_block.html
	 {% if messages %}
              {%  for message in messages %}
              <ul style="color:black;font-size:20px;"><li><div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert" style="color:rgb(0,234,123);">
                  <script> alert("{{ message }}");</script>{{ message }}

              </div></li></ul>
              {% endfor %}
			{% endif %}

TRS_Web/Tourism/templates/Tourism/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
	<style>
		@import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
		@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
	</style>
	<link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
</head>
<body><br><br><br>
	<header class="site-header" id="header">
		<h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
	</header>

	<div class="main-content">
		<i class="fa fa-check main-content__checkmark" id="checkmark"></i>
		<p class="main-content__body" data-lead-id="main-content-body">Thanks for being you.</p>
	</div>

	<footer class="site-footer" id="footer">
		<p class="site-footer__fineprint" id="fineprint"></p>
	</footer>
<script>
	const myTimeout = setTimeout(mypage, 5000);

	function mypage(){
	window.location.href = "/home";
}
</script>
</body>
</html>