TRS_Web/TRS_Web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('Tourism.urls','customer'), namespace = 'customer')),
    path('Tour-Master/',include(('administrator.urls', 'tour-master'), namespace = 'tour-master')),
]

TRS_Web/administrator/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('home',views.home,name='home'),
    path('',views.login,name='login'),
    path('booking',views.booking,name='booking'),
    path('auth',views.login_check,name='auth'),
    path('log-out',views.logout,name='log-out'),
    path('package',views.package,name='package'),
    path('add-package',views.add_package,name='add-package'),
    path('employee',views.employee,name='employee'),
    path('add-employee',views.add_employee,name='add-employee'),
    path('vehicle-details', views.vehicle_display,name ='vehicle-details'),
    path('hotel-details',views.hotel_details,name='hotel-details'),
    path('del-tour/(<int:mobno>)',views.deleted_tour,name="del-tour"),
    path('bill/(<int:cust_id>)',views.bill,name='bill'),
    path('approve-tour/<slug:pkg_id>/<int:custid>/<int:tour_id>',views.approve_tour,name='approve-tour'),
    path('approve-hotel/(<int:hotel_id>)',views.approve_hotel,name='approve-hotel'),
    path('deny-hotel/(<int:hotel_id>)',views.deny_hotel,name='deny-hotel'),
    path('approve-vehicle/(<int:vehicle_id>)',views.approve_vehicle,name='approve-vehicle'),
    path('deny-vehicle/(<int:vehicle_id>)',views.deny_vehicle,name='deny-vehicle'),
    path('tour-report',views.tourreport,name='tour-report'),
    path('vehicle-report',views.vehiclereport,name='vehicle-report'),
    path('hotel-report',views.hotelreport,name='hotel-report'),

]

TRS_Web/administrator/models.py
from django.db import models

# Create your models here.

TRS_Web/administrator/views.py
from urllib.request import HTTPRedirectHandler
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from Tourism.models import *
from django.db import connection
from django.contrib import messages

# Create your views here.

def tourreport(request):
    query = 'SELECT * From tour_registration,tourism_plan where tour_registration.customer_selected_package = tourism_plan.plan_id;'
    data = TourRegistration.objects.raw(query)
    context ={
        'tour_data' : data,
    }
    return render(request,'administrator/report.html',context)
def hotelreport(request):
    data = HotelBooking.objects.all()
    context ={
        'hotel_data' : data,
    }
    return render(request,'administrator/report.html',context)
def vehiclereport(request):
    data = VehicleRegistration.objects.all()
    context ={
        'vehicle_data' : data,
    }
    return render(request,'administrator/report.html',context)


def login(request):
    return render(request,'administrator/login.html')

def bill(request,cust_id):
    tour = TourRegistration.objects.get(id = cust_id)
    payment = Payment.objects.get(tour_id = cust_id)
    plan = TourismPlan.objects.get(plan_id = tour.customer_selected_package )
    context = {
        'invoice_number' : payment.id,
        'invoice_date'   : payment.paid_date,
        'customer_name'  : tour.customer_name,
        'customer_address' : tour.customer_address,
        'customer_phone'  : tour.customer_phone,
        'package_name'   : plan.plan_name,
        'trip_duration'  : plan.plan_duration,
        'total_amount'   : payment.paid_amount,
        'description'    : plan.plan_details,
        'payment_status' : payment.paid_status

    }
    return render(request,'administrator/bill.html',context)


def login_check(request):
    try:
        employee_id = request.POST.get('email')
        employee_pw = request.POST.get('password')
        if employee_id == '' and employee_pw == '':
            messages.warning(request, 'Fields Are Empty !!')
            return render(request, 'administrator/login.html')
        else:
            login  = TrsEmployee.objects.get(emp_username=employee_id,emp_password=employee_pw)
            print(login)
            messages.add_message(request,messages.SUCCESS, 'Login Successfully!!')
            request.session['admin_username'] = employee_id
            emps_type = TrsEmployee.objects.get(emp_username=employee_id)
            print(emps_type.emp_type)
            return HttpResponseRedirect("/Tour-Master/home",{'username':request.session['admin_username'],'emp_status':emps_type.emp_type})
    except TrsEmployee.DoesNotExist:
        messages.add_message(request,messages.SUCCESS,"Login Failed !!")
        return HttpResponseRedirect("/Tour-Master/")

def logout(request):
    try:
        request.session.flush()
        return HttpResponseRedirect('/Tour-Master/')
    except:
        return HttpResponse("<h1>ERROR</h1>")

def home(request):
    cursor = connection.cursor()
    total_tour_booking=TourRegistration.objects.count()
    total_hotel_booking=HotelBooking.objects.count()
    total_vehicle_booking=VehicleRegistration.objects.count()
    total_payment = Payment.objects.count()
    context = {
       'tour_count':total_tour_booking,
       'hotel_count':total_hotel_booking,
       'total_vehicle':total_vehicle_booking,
       'total_payment':total_payment,
    }
    
    return render(request,'administrator/index.html',context)

def booking(request):
    booked = TourRegistration.objects.raw("select * from tour_registration where trip_status = 1 ")
    booked_completed = TourRegistration.objects.raw("select * from tour_registration where trip_status = 2 ")
    cancelled = TourRegistration.objects.raw("select * from tour_registration where trip_status = 3")
    return render(request,'administrator/orders.html',{'booked':booked,'completed':booked_completed,'cancelled':cancelled})

def package(request):
    return render(request,'administrator/package.html')

def add_package(request):
    if request.POST:
        tour_name = request.POST['package_name']
        tour_amount = request.POST['package_amount']
        tour_duration = request.POST['package_duration']
        tour_details = request.POST['package_details']
        Package = TourismPlan(plan_name = tour_name,
                            plan_details = tour_details,
                            plan_duration = tour_duration,
                            plan_amount = tour_amount)
        Package.save()
        messages.add_message(request,messages.SUCCESS,"Package Added Successfully !!")
        import time
        time.sleep(3)
        return HttpResponseRedirect("/Tour-Master/package")
    else:
        messages.add_message(request,messages.ERROR,"Failed For Some Reason !!")
        return HttpResponseRedirect("/Tour-Master/package")
    

def vehicle_display(request):
    record = VehicleRegistration.objects.all()
    return render(request,'administrator/vehicle_display.html',{'record':record})

def deleted_tour(request,mobno):
    regDel = TourRegistration.objects.get(id = mobno) 
    regDel.delete()
    messages.add_message(request,messages.SUCCESS,"Customer Data Deleted !!")
    return HttpResponseRedirect("/Tour-Master/booking")

def approve_tour(request,pkg_id,custid,tour_id):
    import datetime
    trip_amt = TourismPlan.objects.get(plan_id = pkg_id)
    customer = CustomerDetails.objects.get(customer_id = custid)
    tour = TourRegistration.objects.get(id = tour_id)
    tour.trip_status = 2
    tour.save()
    appCust = Payment(
        paid_date = datetime.datetime.now(),
        paid_amount =  trip_amt.plan_amount,
        paid_status = 0,
        paid_by = customer.customer_id,
        tour_id = tour_id
    )
    appCust.save()
    return HttpResponseRedirect("/Tour-Master/booking")
def hotel_details(request):
    record = HotelBooking.objects.all()
    return render(request,'administrator/hotel_details.html', {'record':record})
def approve_hotel(request,hotel_id):
    hotel = HotelBooking.objects.get(id = hotel_id)
    hotel.hotel_status = 0
    hotel.save()
    return HttpResponseRedirect('/Tour-Master/Hotel-details')
def deny_hotel(request,hotel_id):
    hotel = HotelBooking.objects.get(id = hotel_id)
    hotel.delete()
    return HttpResponseRedirect('/Tour-Master/hotel-details')
def approve_vehicle(request,vehicle_id):
    vehicle = VehicleRegistration.objects.get(id = vehicle_id)
    vehicle.vehicle_status = 0
    vehicle.save()
    return HttpResponseRedirect('/Tour-Master/vehicle-details')
def deny_vehicle(request,vehicle_id):
    vehicle = VehicleRegistration.objects.get(id = vehicle_id)
    vehicle.delete()
    return HttpResponseRedirect('/Tour-Master/vehicle-details')

def employee(request):
    return render(request,'administrator/register_employee.html')

def add_employee(request):
    if request.POST:
        emp_name = request.POST['firstname'] + " "+request.POST['lastname']
        emp_address = request.POST['address']
        emp_dob = request.POST['dob']
        emp_email = request.POST['email']
        emp_phone = request.POST['phone']
        emp_sal =  request.POST['salary']
        emp_type = request.POST['emp_type']
        emp_username = request.POST['username']
        emp_password = request.POST['password']
        employee = TrsEmployee(
            emp_name = emp_name,
            emp_address = emp_address,
            emp_dob =  emp_dob,
            emp_email = emp_email,
            emp_mobno = emp_phone,
            emp_sal = emp_sal,
            emp_type = emp_type,
            emp_username = emp_username,
            emp_password = emp_password
        )
        employee.save()
        messages.add_message(request,messages.SUCCESS,"Employee Added Successfully !!")
        return HttpResponseRedirect("/Tour-Master/employee")
    else:
        return HttpResponseRedirect("/Tour-Master/employee")

TRS_Web/administrator/templates/administrator/login.html
<!DOCTYPE html>
<html lang="en"> 
<head>
	{% load static %}
    <title>Tour Master login</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
   
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'plugins/fontawesome/js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">

</head> 

<body class="app app-login p-0">    	
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="{% url 'tour-master:home' %}"><img class="logo-icon me-2" src="{% static 'images/app-logo.svg' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">Log in to Portal</h2>
			        <div class="auth-form-container text-start">
						<form action="{% url 'tour-master:auth' %}" method = "POST">  
							{% csrf_token %}       
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Email</label>
								<input id="signin-email" name="email" type="text" class="form-control signin-email" placeholder="Username" required="required">
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Password</label>
								<input id="signin-password" name="password" type="password" class="form-control signin-password" placeholder="Password" required="required">
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											Remember me
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-end">
											<a href="reset-password.html">Forgot password?</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary w-100 theme-btn mx-auto">Log In</button>
							</div>
							{% include 'administrator/messages.html' %}
						</form>
						
						<div class="auth-option text-center pt-5">No Account? Sign up <a class="text-link" href="signup.html" >here</a>.</div>
					</div><!--//auth-form-container-->	

			    </div><!--//auth-body-->
		    
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">
		    </div>
		    <div class="auth-background-mask"></div>
		    
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->


</body>
</html> 

TRS_Web/administrator/templates/administrator/messages.html
{% if messages %}
{%  for message in messages %}
<ul style="color:black;font-size:12px;margin-left:0%; width:80%;font-weight:bolder;"><li><div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert" style="margin-left:0%;">
   {{ message }}
</div></li></ul>
{% endfor %}
{% endif %}

TRS_Web/administrator/templates/administrator/nav.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<header class="app-header fixed-top">	   	            
    <div class="app-header-inner">  
        <div class="container-fluid py-2">
            <div class="app-header-content"> 
                <div class="row justify-content-between align-items-center">
                
                <div class="col-auto">
                    <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
                    </a>
                </div><!--//col-->
                <div class="search-mobile-trigger d-sm-none col">
                    <i class="search-mobile-trigger-icon fa-solid fa-magnifying-glass"></i>
                </div><!--//col-->
                Travel Master
                <div class="app-utilities col-auto">
                    <div class="app-utility-item app-notifications-dropdown dropdown">    
                        <br />
                    <div class="app-utility-item app-user-dropdown dropdown">
                        <a class="dropdown-toggle" id="user-dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"> {{ request.session.admin_username }}</a>
                        <ul class="dropdown-menu" aria-labelledby="user-dropdown-toggle">
                            <li><a class="dropdown-item" href="{% url 'tour-master:log-out' %}">Log Out</a></li>
                        </ul>
                    </div><!--//app-user-dropdown--> 
                </div><!--//app-utilities-->
            </div><!--//row-->
            </div><!--//app-header-content-->
        </div><!--//container-fluid-->
    </div><!--//app-header-inner-->
    <div id="app-sidepanel" class="app-sidepanel"> 
        <div id="sidepanel-drop" class="sidepanel-drop"></div>
        <div class="sidepanel-inner d-flex flex-column">
            <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
            <div class="app-branding">
                <a class="app-logo" href="{% url  'tour-master:home' %}"><img class="logo-icon me-2" src="{% static 'images/app-logo.svg' %}" alt="logo"><span class="logo-text">TRAVEL MASTER</span></a>

            </div><!--//app-branding-->  
            
            <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
                <ul class="app-menu list-unstyled accordion" id="menu-accordion">
                    <li class="nav-item">
                        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
                        <a class="nav-link active" href="{% url 'tour-master:home' %}">
                            <span class="nav-icon">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house-door" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M7.646 1.146a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5H9.5a.5.5 0 0 1-.5-.5v-4H7v4a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6zM2.5 7.707V14H6v-4a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5v4h3.5V7.707L8 2.207l-5.5 5.5z"/>
      <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
    </svg>
                             </span>
                             <span class="nav-link-text">Home</span>
                        </a><!--//nav-link-->
                    </li><!--//nav-item-->
                    <li class="nav-item">
                        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
                        <a class="nav-link" href="{% url 'tour-master:booking' %}">
                            <span class="nav-icon">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
<path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
<circle cx="3.5" cy="5.5" r=".5"/>
<circle cx="3.5" cy="8" r=".5"/>
<circle cx="3.5" cy="10.5" r=".5"/>
</svg>
                             </span>
                             <span class="nav-link-text">Booking</span>
                        </a><!--//nav-link-->
                    </li><!--//nav-item-->
                    <li class="nav-item">
                        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
                        <a class="nav-link" href="{% url 'tour-master:package' %}">
                            <span class="nav-icon">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
<path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
<circle cx="3.5" cy="5.5" r=".5"/>
<circle cx="3.5" cy="8" r=".5"/>
<circle cx="3.5" cy="10.5" r=".5"/>
</svg>
                             </span>
                             <span class="nav-link-text">Package</span>
                        </a><!--//nav-link-->
                    </li><!--//nav-item-->
                    <li class="nav-item">
                        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
                        <a class="nav-link" href="{% url 'tour-master:employee' %}">
                            <span class="nav-icon">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
<path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
<circle cx="3.5" cy="5.5" r=".5"/>
<circle cx="3.5" cy="8" r=".5"/>
<circle cx="3.5" cy="10.5" r=".5"/>
</svg>
                             </span>
                             <span class="nav-link-text">Add Employee </span>
                        </a><!--//nav-link-->
                    </li><!--//nav-item-->
                    <li class="nav-item">
                        <!--//Bootstrap Icons: https://icons.getbootstrap.com/ -->
                        <a class="nav-link" href="{% url 'tour-master:vehicle-details' %}">
                            <span class="nav-icon">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
<path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
<circle cx="3.5" cy="5.5" r=".5"/>
<circle cx="3.5" cy="8" r=".5"/>
<circle cx="3.5" cy="10.5" r=".5"/>
</svg>
                             </span>

                             <span class="nav-link-text">Vehicle Details </span>


                             <a class="nav-link" href="{% url 'tour-master:hotel-details' %}">
                                <span class="nav-icon">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
    <path fill-rule="evenodd" d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5z"/>
    <circle cx="3.5" cy="5.5" r=".5"/>
    <circle cx="3.5" cy="8" r=".5"/>
    <circle cx="3.5" cy="10.5" r=".5"/>
    </svg>
                                 </span>
    
                                 <span class="nav-link-text">Hotel details </span>
    
                                 

                                 <a class="nav-link" href="{% url 'tour-master:tour-report' %}">
                                    <span class="nav-icon">
                                        <i class="bi-file-earmark-text" style="font-size: 20px;"></i>
                                     </span>
        
                                     <span class="nav-link-text">Tour Report </span> 
                                     <a class="nav-link" href="{% url 'tour-master:hotel-report' %}">
                                        <span class="nav-icon">
                                            <i class="bi-file-earmark-text" style="font-size: 20px;"></i>
                                         </span>
            
                                         <span class="nav-link-text">Hotel Report </span> 
                                         <a class="nav-link" href="{% url 'tour-master:vehicle-report' %}">
                                            <span class="nav-icon">
                                                <i class="bi-file-earmark-text" style="font-size: 20px;"></i>
                                             </span>
                
                                             <span class="nav-link-text">Vehicle Report </span> 
                            
    
    



                        </a><!--//nav-link-->
                    </li><!--//nav-item-->
                    
        </div><!--//sidepanel-inner-->
    </div><!--//app-sidepanel-->
</header><!--//app-header-->